CREATE DATABASE tarea_final;

CREATE TABLE IF NOT EXISTS hamburguesas(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    precio integer NOT NULL,
    descripcion text,
    imagen text
);

CREATE TABLE IF NOT EXISTS ingredientes(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    descripcion text
);

INSERT INTO hamburguesas(nombre, precio, descripcion, imagen)
    VALUES( 'Cuarto de libra', 3000, 'Ñami', 'cuartp.png');


INSERT INTO ingredientes(nombre, descripcion)
    VALUES('Bacon', 'yummy pork');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('MAKE a photo', 3, ' nodejs', '2000-05-12');

INSERT INTO tasks(name, done, projectId)
    VALUES('DOWNLOAD VUEJS', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('DOWNLOAD nj', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('create db', false, 2);


INSERT INTO tasks(name, done, projectId)
    VALUES(' db', false, 2);